name: proj1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.14
  image_picker: ^1.1.1
  shared_preferences: ^2.3.2
  flutter_staggered_grid_view: ^0.7.0
  http: ^1.1.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  share_plus: ^10.0.2
  cupertino_icons: ^1.0.8
  animated_splash_screen: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  hive_generator: ^2.0.1
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1  # <-- Added here

# Flutter launcher icons configuration
flutter_icons:
  android: true
  ios: true
  image_path: "assets/Pictures/read.png"  # <-- Update this path to your logo image

flutter:
  uses-material-design: true

  assets:
    - assets/images/
